name: Terraform AWS CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        options:
          - apply
          - destroy

      aws_region:
        description: "AWS Region"
        required: true

      backend_bucket:
        description: "Terraform State S3 Bucket"
        required: true

      backend_key:
        description: "Terraform State File Key"
        required: true

      project_name:
        description: "Project Name"
        required: true

      ami_id:
        description: "AMI ID"
        required: true

      instance_type:
        description: "EC2 Instance Type"
        required: true

      key_pair_name:
        description: "EC2 Key Pair Name"
        required: true

      allowed_ssh_cidr:
        description: "Allowed SSH CIDR"
        required: true

      bucket_suffix:
        description: "Bucket Suffix"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ${{ github.event.inputs.aws_region }}
      TF_VAR_project_name: ${{ github.event.inputs.project_name }}
      TF_VAR_ami_id: ${{ github.event.inputs.ami_id }}
      TF_VAR_instance_type: ${{ github.event.inputs.instance_type }}
      TF_VAR_key_pair_name: ${{ github.event.inputs.key_pair_name }}
      TF_VAR_allowed_ssh_cidr: ${{ github.event.inputs.allowed_ssh_cidr }}
      TF_VAR_bucket_suffix: ${{ github.event.inputs.bucket_suffix }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ github.event.inputs.backend_bucket }}" \
            -backend-config="key=${{ github.event.inputs.backend_key }}" \
            -backend-config="region=${{ github.event.inputs.aws_region }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve